language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

env:
  global:
    - COMPOSER_GLOBAL_FLAGS='--prefer-source --no-interaction --no-scripts --no-progress --no-suggest'
  matrix:
    - COMPOSER_FLAGS='--prefer-lowest'
    - COMPOSER_FLAGS='--prefer-stable'

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini ; fi
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo
  - composer self-update --stable --no-progress

install:
  - travis_retry composer update --profile $COMPOSER_GLOBAL_FLAGS $COMPOSER_FLAGS
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" ]]; then travis_retry composer require alcaeus/mongo-php-adapter --profile $COMPOSER_GLOBAL_FLAGS --ignore-platform-reqs ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then travis_retry composer require satooshi/php-coveralls:dev-master $COMPOSER_GLOBAL_FLAGS ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then vendor/bin/phpcs --standard=PSR2 src tests ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then vendor/bin/phpmd src text phpmd.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then vendor/bin/phpcpd src ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then vendor/bin/phpunit --coverage-clover .build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" ]]; then vendor/bin/phpunit ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then travis_retry php vendor/bin/coveralls --coverage_clover .build/logs/clover.xml --verbose ; fi
